### PR TITLE
fix Label to work with Substrings

### LINKED ISSUE #2070: `Label` fails if `text` is of type `SubString{String}`
Hello,

On `Julia` v1.7.3 and `CairoMakie` v0.8.6 (`Makie` v0.17.6) I get an error with the following code:
```julia
julia> using CairoMakie

julia> fig = Figure()
Scene (800px, 600px):
  0 Plots
  0 Child Scenes

julia> title1, title2 = split("name1.name2", ".")
2-element Vector{SubString{String}}:
 "name1"
 "name2"

julia> Label(fig[1,1], text=title1)
ERROR: MethodError: no method matching _get_glyphcollection_and_linesegments(::SubString{String}, ::Int64, ::Float32, ::FreeTypeAbstraction.FTFont, ::Tuple{Symbol, Symbol}, ::Quaternionf, ::Symbol, ::Float32, ::ColorTypes.RGBA{Float32}, ::ColorTypes.RGBA{Float32}, ::Int64, ::Float32)
Closest candidates are:
  _get_glyphcollection_and_linesegments(::String, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/Makie/xVGV7/src/basic_recipes/text.jl:68
  _get_glyphcollection_and_linesegments(::LaTeXStrings.LaTeXString, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/Makie/xVGV7/src/basic_recipes/text.jl:72
Stacktrace:
  [1] (::ComposedFunction{Makie.var"#push_args#1777"{Vector{Int64}, Vector{ColorTypes.RGBA{Float32}}, Vector{Float32}, Vector{Point{2, Float32}}, Vector{Makie.GlyphCollection}}, typeof(Makie._get_glyphcollection_and_linesegments)})(::SubString{String}, ::Vararg{Any}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./operators.jl:1085
  [2] (::ComposedFunction{Makie.var"#push_args#1777"{Vector{Int64}, Vector{ColorTypes.RGBA{Float32}}, Vector{Float32}, Vector{Point{2, Float32}}, Vector{Makie.GlyphCollection}}, typeof(Makie._get_glyphcollection_and_linesegments)})(::SubString{String}, ::Vararg{Any})
    @ Base ./operators.jl:1085
  [3] macro expansion
    @ ~/.julia/packages/Makie/xVGV7/src/utilities/utilities.jl:198 [inlined]
  [4] broadcast_foreach(::ComposedFunction{Makie.var"#push_args#1777"{Vector{Int64}, Vector{ColorTypes.RGBA{Float32}}, Vector{Float32}, Vector{Point{2, Float32}}, Vector{Makie.GlyphCollection}}, typeof(Makie._get_glyphcollection_and_linesegments)}, ::SubString{String}, ::UnitRange{Int64}, ::Float32, ::FreeTypeAbstraction.FTFont, ::Tuple{Symbol, Symbol}, ::Quaternionf, ::Symbol, ::Float32, ::ColorTypes.RGBA{Float32}, ::ColorTypes.RGBA{Float32}, ::Int64, ::Float32)
    @ Makie ~/.julia/packages/Makie/xVGV7/src/utilities/utilities.jl:184
  [5] (::Makie.var"#1773#1776"{Base.RefValue{Vector{Int64}}, Observable{Vector{ColorTypes.RGBA{Float32}}}, Observable{Vector{Float32}}, Observable{Vector{Point{2, Float32}}}, Observable{Vector{Makie.GlyphCollection}}})(str::SubString{String}, ts::Float32, f::FreeTypeAbstraction.FTFont, al::Tuple{Symbol, Symbol}, rot::Float32, jus::Symbol, lh::Float32, col::ColorTypes.RGBA{Float32}, scol::Tuple{Symbol, Float64}, swi::Int64, www::Float32)
    @ Makie ~/.julia/packages/Makie/xVGV7/src/basic_recipes/text.jl:34
  [6] (::Observables.var"#callback#13"{Makie.var"#1773#1776"{Base.RefValue{Vector{Int64}}, Observable{Vector{ColorTypes.RGBA{Float32}}}, Observable{Vector{Float32}}, Observable{Vector{Point{2, Float32}}}, Observable{Vector{Makie.GlyphCollection}}}, NTuple{11, Observable{Any}}})(x::Any)
    @ Observables ~/.julia/packages/Observables/ynr7h/src/Observables.jl:339
  [7] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
  [8] invokelatest
    @ ./essentials.jl:714 [inlined]
  [9] notify(observable::Observables.AbstractObservable)
    @ Observables ~/.julia/packages/Observables/ynr7h/src/Observables.jl:143
 [10] plot!(plot::MakieCore.Text{Tuple{Vector{Point{3, Float32}}}})
    @ Makie ~/.julia/packages/Makie/xVGV7/src/basic_recipes/text.jl:53
 [11] plot!(scene::Scene, P::Type{MakieCore.Text{Tuple{Point{3, Float32}}}}, attributes::Attributes, input::Tuple{Observable{Point{3, Float32}}}, args::Observable{Tuple{Vector{Point{3, Float32}}}})
    @ Makie ~/.julia/packages/Makie/xVGV7/src/interfaces.jl:402
 [12] plot!(scene::Scene, P::Type{MakieCore.Text}, attributes::Attributes, args::Observable{Point{3, Float32}}; kw_attributes::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/xVGV7/src/interfaces.jl:320
 [13] plot!
    @ ~/.julia/packages/Makie/xVGV7/src/interfaces.jl:288 [inlined]
 [14] #plot!#132
    @ ~/.julia/packages/Makie/xVGV7/src/interfaces.jl:271 [inlined]
 [15] #text!#52
    @ ~/.julia/packages/MakieCore/4Hq26/src/recipes.jl:37 [inlined]
 [16] initialize_block!(l::Label)
    @ Makie ~/.julia/packages/Makie/xVGV7/src/makielayout/blocks/label.jl:11
 [17] _block(::Type{Label}, ::Figure; bbox::Nothing, kwargs::Base.Pairs{Symbol, SubString{String}, Tuple{Symbol}, NamedTuple{(:text,), Tuple{SubString{String}}}})
    @ Makie ~/.julia/packages/Makie/xVGV7/src/makielayout/blocks.jl:393
 [18] _block(::Type{Label}, ::GridPosition; kwargs::Base.Pairs{Symbol, SubString{String}, Tuple{Symbol}, NamedTuple{(:text,), Tuple{SubString{String}}}})
    @ Makie ~/.julia/packages/Makie/xVGV7/src/makielayout/blocks.jl:284
 [19] #_#1001
    @ ~/.julia/packages/Makie/xVGV7/src/makielayout/blocks.jl:269 [inlined]
 [20] top-level scope
    @ REPL[6]:1
```

### PR DESCRIPTION
**Pull request by fatteneder**
# Description

Fixes #2070 

## Type of change

Delete options that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

### CODE REVIEW

File: src/basic_recipes/text.jl [hunk 1]
```diff
@@ -65,7 +65,7 @@ function plot!(plot::Text)
     plot
 end
 
-function _get_glyphcollection_and_linesegments(string::String, index, ts, f, al, rot, jus, lh, col, scol, swi, www)
+function _get_glyphcollection_and_linesegments(string::AbstractString, index, ts, f, al, rot, jus, lh, col, scol, swi, www)
     gc = layout_text(string, ts, f, al, rot, jus, lh, col, scol, swi, www)
```
Comment (asinghvi17) [inline src/basic_recipes/text.jl:69]:
```suggestion
function _get_glyphcollection_and_linesegments(str::AbstractString, index, ts, f, al, rot, jus, lh, col, scol, swi, www)
    gc = layout_text(string(str), ts, f, al, rot, jus, lh, col, scol, swi, www)
```

Probably best to be on the safe side here.  Not sure if this would error with substrings.

Comment (fatteneder) [reply src/basic_recipes/text.jl:69]: `string(str)` makes a copy of `str` if it is a `SubString` and returns a `String`, so this should work. In case one wants to update the text by changing the view of the `SubString` one should already pass in an `Observable`, I guess.

However, `layout_text` is already typed with  `AbstractString`. If it expects only a `String` then we should update the signature there too, or? Alternatively, we could move the `string` into `layout_text`. `string(str)` is a no-op if `str isa String`.

Comment (jkrumbiegel) [reply src/basic_recipes/text.jl:69]: I mean realistically if one has an AbstractString that does not behave like String/Substring for all usual operations then `layout_text` will just not work. Or like in the case of LaTeXString needs its own layout function anyway. So conversion to string is probably fine.

**Review by jkrumbiegel — APPROVED** [review]
