### PR TITLE
Finish svg surface so that Cairo callback doesn't potentially hit invalid io later

### LINKED ISSUE #4970: `sprint` with a CairoMakie svg surface causes finalizer errors in 1.11 and above
MWE where `@makie` just contains dev versions of all Makie packages, and `+release` is 1.11.5 at this time (but I checked some others and e.g. 1.11.2 and nightly also show the error, 1.10.5 doesn't).

```julia
sprint(io -> show(io, "image/svg+xml", Scene())); GC.gc()
```

<details>
<summary>The long stacktrace</summary>

```julia
julia +release --project=@makie -e 'using CairoMakie; sprint(io -> show(io, "image/svg+xml", Scene())); GC.gc();'
Precompiling CairoMakie...
  1 dependency successfully precompiled in 12 seconds. 271 already precompiled.
error in running finalizer: BoundsError(a=MemoryRef(offset=0, ptr_or_offset=0x10ee5fb78, mem=Memory{UInt8}(0, 0x10ee5fb78)[], i=1)
ijl_bounds_error_int at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/rtutils.c:205
memoryref at ./boot.jl:523 [inlined]
unsafe_copyto! at ./genericmemory.jl:139 [inlined]
copyto! at ./genericmemory.jl:175 [inlined]
_resize! at ./iobuffer.jl:319
ensureroom at ./iobuffer.jl:401 [inlined]
unsafe_write at ./iobuffer.jl:522
unsafe_write at ./io.jl:803 [inlined]
write_to_stream_callback at /Users/krumbiegel/.julia/packages/Cairo/FQrbN/src/Cairo.jl:151
unknown function (ip: 0x1181a88b7)
closure_write at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_output_stream_write at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_output_stream_vprintf at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_output_stream_printf at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_svg_document_finish at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_svg_surface_finish at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_surface_finish at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
cairo_surface_finish at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_paginated_surface_finish at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
_cairo_surface_finish at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
cairo_surface_destroy at /Users/krumbiegel/.julia/artifacts/210d443a7c5fea7d01dd33a1d093d76e47dc9fd5/lib/libcairo.2.dylib (unknown line)
destroy at /Users/krumbiegel/.julia/packages/Cairo/FQrbN/src/Cairo.jl:249
unknown function (ip: 0x1182740ff)
run_finalizer at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/gc.c:303
jl_gc_run_finalizers_in_list at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/gc.c:393
run_finalizers at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/gc.c:439
ijl_gc_collect at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/gc.c:3915
gc at ./gcutils.jl:133 [inlined]
gc at ./gcutils.jl:133
unknown function (ip: 0x11828004f)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/./julia.h:2157 [inlined]
do_call at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/interpreter.c:126
eval_stmt_value at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/interpreter.c:174
eval_body at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/interpreter.c:666
jl_interpret_toplevel_thunk at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/interpreter.c:824
top-level scope at none:1
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/toplevel.c:943
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/toplevel.c:886
jl_toplevel_eval_flex at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/toplevel.c:886
ijl_toplevel_eval at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/toplevel.c:952 [inlined]
ijl_toplevel_eval_in at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/toplevel.c:994
eval at ./boot.jl:430 [inlined]
exec_options at ./client.jl:296
_start at ./client.jl:531
jfptr__start_73721.1 at /Users/krumbiegel/.julia/juliaup/julia-1.11.5+0.aarch64.apple.darwin14/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/./julia.h:2157 [inlined]
true_main at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/jlapi.c:900
jl_repl_entrypoint at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-HL2F7YQ3XH.0/build/default-honeycrisp-HL2F7YQ3XH-0/julialang/julia-release-1-dot-11/src/jlapi.c:1059
```

</details>

I haven't 100% understood the bug yet, but here's my current progress of debugging
- Cairo.jl registers a finalizer on all surface objects, this finalizer calls this callback https://github.com/JuliaGraphics/Cairo.jl/blob/228a87264c82187710bbef4ab880472b132b9c38/src/Cairo.jl#L150-L153
- when finalized, the callback potentially attempts to write on the io that the surface was created for
- when this finalization happens outside of `sprint`, then a resize operation on the underlying io data fails with a `BoundsError`, probably because the array is already truncated as its content is transferred into a `String`

I didn't manage yet to make an even simpler MWE than `sprint(io -> show(io, "image/svg+xml", Scene())); GC.gc()` with the underlying primitives. I'm also not sure why the bug only showed up after `Memory` was introduced in 1.11, arguably a write out of bounds should have errored in 1.10, too.

### PR DESCRIPTION
**Pull request by jkrumbiegel**
Fixes #4970 although I don't completely understand the mechanism behind it. But the EPS and PDF routines also `finish` their surfaces, so at least there's precedence for doing this and it fixes a test that can be reliably made to fail otherwise. So that's good enough for me at this point, I'd rather not debug Cairo C callbacks interacting with the `Memory` system if I don't have to.

### CODE REVIEW

**Review by asinghvi17 — APPROVED** [review]
This is a pretty common thing I run into with C wrappers, makes sense to me.

It may be worth it to note, that this could also be because of a GC change (if two finalizers interfere with each other, or something gets finalized internally in Cairo)...

File: CairoMakie/test/svg_tests.jl [hunk 1]
```diff
@@ -70,3 +70,10 @@ end
     rm("test1.svg")
     rm("test2.svg")
 end
+
+@testset "issue 4970" begin
+    @test_nowarn begin
+        sprint(io -> show(io, "image/svg+xml", Scene()))
+        GC.gc()
+    end
+end
```
Comment (asinghvi17) [inline CairoMakie/test/svg_tests.jl:79]: Let's test this for all mimes!

```suggestion
@testset "issue 4970" begin
    for mime in CairoMakie.SUPPORTED_MIMES
        @testset "$mime" begin 
            @test_nowarn begin
                sprint(io -> show(io, mime, Scene()))
                GC.gc(true)
           end
        end
    end
end
```

Comment (jkrumbiegel) [reply CairoMakie/test/svg_tests.jl]: moved the test to another file with the loop
